name: CI-CD-Workshop

on:
  push:
    branches:
      # Only run workflow on v1.0, v15.3 or v7.09 branch
      - 'v[0-9]+.[0-9]+'

jobs:
  success_build:
    # Check if the commit message contains #norun and if it does, skip the workflow and if CONDITION is set 'SUCCESS' it will run the workflow otherwise skip the workflow
    if: ${{ vars.CONDITION == 'SUCCESS' && startsWith(github.event.head_commit.message, '#norun') != true }}
    runs-on: ubuntu-latest
    steps:
    # Check out the code
    - name: Check out the code
      uses: actions/checkout@v3

    # Scan for Vulnerabilities with Trivy
    - name: Scan for Vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        severity: 'CRITICAL'

    # Get the requirements to build the image
    - name: Set up QEMU
      id: docker
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # Login to docker
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    # Build and push the image
    - name: Build and push
      uses: docker/build-push-action@v5
      id: build-and-push
      with:
        push: true
        tags: ywaychitaung/ci-cd-workshop:${{ github.sha }}

    # Install Cosign
    - name: Install cosign
      uses: sigstore/cosign-installer@2.2.0
      with:
        cosign-release: 'v2.2.0'

    # Sign image with a key
    - name: Sign image with a key
      run: |
        cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
      env:
        TAGS: ywaychitaung/ci-cd-workshop:${{ github.sha }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}

    # Send Slack notification
    - name: Send GitHub Action trigger data to Slack workflow
      uses: rtCamp/action-slack-notify@v2
      env:
          SLACK_TITLE: "Image build and signed"
          SLACK_MESSAGE: |
            Name: Yway Chit Aung
            Matriculation: A0287270Y
            Email: e1285216@u.nus.edu
            GitHub: https://github.com/ywaychitaung/CI-CD-Workshop.git
            Docker: https://hub.docker.com/repository/docker/ywaychitaung/ci-cd-workshop/general
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

  fail_build:
    # Check if the commit message contains #norun and if it does, skip the workflow and if CONDITION is set 'FAIL' it will run the workflow otherwise skip the workflow
    if: ${{ vars.CONDITION == 'FAIL' && startsWith(github.event.head_commit.message, '#norun') != true }}
    runs-on: ubuntu-latest
    steps:
    # Check out the code
    - name: Check out the code
      uses: actions/checkout@v3

    # Scan for Vulnerabilities with Trivy 
    - name: Scan for Vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        output: 'trivy-results.txt'
        severity: 'HIGH'

    # Send Slack notification
    - name: Send GitHub Action trigger data to Slack workflow
      uses: rtCamp/action-slack-notify@v2
      env:
          SLACK_COLOR: '#FF0000'
          SLACK_TITLE: "Scan failed - Yway Chit Aung"
          SLACK_MESSAGE: |
            Failed trivy scan, see uploaded report
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

    # Upload file to Slack
    - uses: MeilCli/slack-upload-file@v3
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
        file_path: 'trivy-results.txt'
        initial_comment: 'Scan report by Yway Chit Aung'
        