name: CI-CD-Workshop

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '#norun') != true
    runs-on: ubuntu-latest
    steps:
    - name: Scan for Vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: ${{ vars.SEVERITY }}
    
    - uses: MeilCli/slack-upload-file@v3
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
        content: 'file content'
        file_type: 'text'
        file_name: 'text.txt'
        title: 'title of file'
        initial_comment: 'post by slack-upload-file'
      

    - name: Check out the code
      uses: actions/checkout@v3

    - name: Install cosign
      if: github.event_name != 'pull_request'
      uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06
      with:
        cosign-release: 'v2.1.1'

    - name: Set up QEMU
      id: docker
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ywaychitaung/ci-cd-workshop:${{ github.sha }}

    - name: Send GitHub Action trigger data to Slack workflow
      uses: rtCamp/action-slack-notify@v2
      env:
          SLACK_TITLE: "Image build and signed"
          SLACK_MESSAGE: |
            Name: Yway Chit Aung
            Matriculation: A0287270Y
            Email: e1285216@u.nus.edu
            GitHub: https://github.com/ywaychitaung/CI-CD-Workshop.git
            Docker: https://hub.docker.com/repository/docker/ywaychitaung/ci-cd-workshop/general
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}