name: CI-CD-Workshop

on:
  push:
    branches:
      - 'main'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      id: checkout
      uses: actions/checkout@v4

    - name: Scan for Vulnerabilities
      id: trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        severity: 'CRITICAL'
        output: 'scan_report.txt'
    
    # - name: Set up QEMU
    #   id: docker
    #   uses: docker/setup-qemu-action@v3
    # -
    #   name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
    
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    # - name: Build and push
    #   uses: docker/build-push-action@v5
    #   with:
    #     push: true
    #     tags: user/app:latest

    - name: Send GitHub Action trigger data to Slack workflow
      uses: rtCamp/action-slack-notify@v2.1.0
      env:
          SLACK_TITLE: "Image build and signed"
          SLACK_MESSAGE: |
            Name: Yway Chit Aung
            Matriculation: A0287270Y
            Email: e1285216@u.nus.edu
            GitHub: https://github.com/ywaychitaung/CI-CD-Workshop.git
            Docker: https://hub.docker.com/repository/docker/ywaychitaung/ci-cd-workshop/general
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
            
        
